import argparse
import json
import os
import shutil
import sys
from copy import deepcopy
from pathlib import Path

import cv2
import numpy as np
import torch
from mmcv.parallel import MMDataParallel
from mmcv.runner import load_checkpoint, wrap_fp16_model
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import mmdet
from mmdet.datasets import replace_ImageToTensor
from mmdet3d.core.visualizer.occ_visualization import (make_occ_color_map,
                                                       render_occ_bev)
from mmdet3d.datasets import build_dataloader, build_dataset
from mmdet3d.models import build_model

from tools.infraocc.common import (build_ego_frame_reanchor_matrix,
                                   flatten_results, get_split_cfg,
                                   load_config, load_occ_gt,
                                   warp_semantics_by_reanchor)

if mmdet.__version__ > '2.23.0':
    from mmdet.utils import compat_cfg
else:
    from mmdet3d.utils import compat_cfg


CLASS_NAMES = [
    'others', 'barrier', 'bicycle', 'bus', 'car', 'construction_vehicle',
    'motorcycle', 'pedestrian', 'traffic_cone', 'trailer', 'truck',
    'driveable_surface', 'other_flat', 'sidewalk', 'terrain', 'manmade',
    'vegetation', 'free'
]
DYNAMIC_INDICES = np.array([2, 3, 4, 6, 7, 10], dtype=np.uint8)
EMPTY_IDX = CLASS_NAMES.index('free')
COLOR_MAP = make_occ_color_map(CLASS_NAMES)

DEFAULT_OUTPUT_DIR = (
    ROOT / 'projects' / 'InfraOcc' / 'figures_update' / 'robustness_occ')
DEFAULT_PROJECT_COPY_DIR = (
    ROOT / 'projects' / 'InfraOcc' / 'figures_update' / 'robustness')
DEFAULT_PAPER_FIG_DIR = (
    ROOT / 'docs' / 'TPAMI2026' / 'local-git' / 'figures')

CONDITIONS = [
    ('translation_0.4m', 'Translation 0.4 m',
     dict(translation=(0.4, 0.0, 0.0), roll_deg=0.0, pitch_deg=0.0,
          yaw_deg=0.0)),
    ('translation_0.8m', 'Translation 0.8 m',
     dict(translation=(0.8, 0.0, 0.0), roll_deg=0.0, pitch_deg=0.0,
          yaw_deg=0.0)),
    ('translation_1.2m', 'Translation 1.2 m',
     dict(translation=(1.2, 0.0, 0.0), roll_deg=0.0, pitch_deg=0.0,
          yaw_deg=0.0)),
    ('rotation_0.4deg', 'Rotation 0.4 deg',
     dict(translation=(0.0, 0.0, 0.0), roll_deg=0.0, pitch_deg=0.0,
          yaw_deg=0.4)),
    ('rotation_0.8deg', 'Rotation 0.8 deg',
     dict(translation=(0.0, 0.0, 0.0), roll_deg=0.0, pitch_deg=0.0,
          yaw_deg=0.8)),
    ('rotation_1.2deg', 'Rotation 1.2 deg',
     dict(translation=(0.0, 0.0, 0.0), roll_deg=0.0, pitch_deg=0.0,
          yaw_deg=1.2)),
]


def parse_args():
    parser = argparse.ArgumentParser(
        description='Render Plain(C)/ProSD(C) occupancy robustness examples.')
    parser.add_argument(
        '--sample-index',
        type=int,
        default=24,
        help='Validation sample index used for all perturbation rows.')
    parser.add_argument('--gpu-id', type=int, default=0)
    parser.add_argument(
        '--config-plain',
        default=
        'projects/InfraOcc/configs/main_table_update/infraocc_c_4x4_36e_plain.py'
    )
    parser.add_argument(
        '--ckpt-plain',
        default='projects/InfraOcc/checkpoints_update/c_plain.pth')
    parser.add_argument(
        '--config-prosd',
        default=
        'projects/InfraOcc/configs/main_table_update/infraocc_c_4x4_36e_prosd.py'
    )
    parser.add_argument(
        '--ckpt-prosd',
        default='projects/InfraOcc/checkpoints_update/c_prosd.pth')
    parser.add_argument(
        '--output-dir',
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help='Fresh output directory for per-condition assets and manifest.')
    parser.add_argument(
        '--project-copy-dir',
        type=Path,
        default=DEFAULT_PROJECT_COPY_DIR,
        help='Directory receiving paper-ready project-side PNG/PDF copies.')
    parser.add_argument(
        '--paper-output-dir',
        type=Path,
        default=DEFAULT_PAPER_FIG_DIR,
        help='LaTeX figures directory receiving PNG/PDF copies.')
    parser.add_argument(
        '--output-name',
        default='robustness_occ_qualitative',
        help='Output figure stem.')
    parser.add_argument(
        '--keep-output-dir',
        action='store_true',
        help='Do not remove the output directory before rendering.')
    return parser.parse_args()


def write_reanchor_config(output_path, base_config, perturbation):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    perturbation_repr = json.dumps(perturbation, indent=4)
    output_path.write_text(
        f"""# Auto-generated by tools/infraocc/generate_robustness_occ_qualitative.py
from copy import deepcopy

from mmcv import Config

_base_ = [r'{Path(base_config).as_posix()}']
_base_cfg = Config.fromfile(r'{Path(base_config).as_posix()}')

_base_test_pipeline = getattr(_base_cfg, 'test_pipeline', None)
if _base_test_pipeline is None:
    _base_test_pipeline = _base_cfg.data.test.pipeline
test_pipeline = deepcopy(_base_test_pipeline)
test_pipeline = [
    step for step in test_pipeline
    if not (isinstance(step, dict)
            and step.get('type') == 'InfraOccEgoFrameReanchoring')
]

_perturbation = {perturbation_repr}
test_pipeline.insert(0, dict(
    type='InfraOccEgoFrameReanchoring',
    translation=tuple(_perturbation['translation']),
    roll_deg=float(_perturbation['roll_deg']),
    pitch_deg=float(_perturbation['pitch_deg']),
    yaw_deg=float(_perturbation['yaw_deg']),
))

data = dict(
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))
evaluation = dict(interval=2, pipeline=test_pipeline)
""",
        encoding='utf-8')


def build_model_runner(config_path, checkpoint_path, gpu_id):
    cfg = compat_cfg(load_config(config_path))
    cfg.model.pretrained = None
    cfg.gpu_ids = [gpu_id]
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
    fp16_cfg = cfg.get('fp16', None)
    if fp16_cfg is not None:
        wrap_fp16_model(model)
    load_checkpoint(model, str(checkpoint_path), map_location='cpu')
    model = MMDataParallel(model.cuda(gpu_id), device_ids=[gpu_id])
    model.eval()
    return cfg, model


def build_condition_loader(config_path):
    cfg = compat_cfg(load_config(config_path))
    split_cfg = get_split_cfg(cfg, 'test')
    test_loader_cfg = cfg.data.get('test_dataloader', {})
    samples_per_gpu = int(test_loader_cfg.get('samples_per_gpu', 1))
    if isinstance(split_cfg, dict) and samples_per_gpu > 1:
        split_cfg.pipeline = replace_ImageToTensor(split_cfg.pipeline)
    dataset = build_dataset(split_cfg)
    data_loader = build_dataloader(
        dataset,
        samples_per_gpu=1,
        workers_per_gpu=0,
        dist=False,
        shuffle=False,
        runner_type='EpochBasedRunnerEval')
    return cfg, dataset, data_loader


def first_batch_by_index(data_loader, index):
    for data in data_loader:
        metas = data['img_metas'][0].data[0]
        sample_index = int(metas[0]['index'])
        if sample_index == int(index):
            return data
    raise KeyError(f'Sample index {index} was not found in the test loader.')


def run_one_prediction(model, data_loader, index):
    data = first_batch_by_index(data_loader, index)
    with torch.no_grad():
        outputs = model(return_loss=False, rescale=True, **data)
    flat = flatten_results(outputs)
    for item in flat:
        if int(item['index']) == int(index):
            return np.asarray(item['occ_results'], dtype=np.uint8)
    raise RuntimeError(f'Model output did not contain sample index {index}.')


def dynamic_only(semantics):
    semantics = np.asarray(semantics, dtype=np.uint8)
    masked = np.full_like(semantics, fill_value=EMPTY_IDX)
    dyn_mask = np.isin(semantics, DYNAMIC_INDICES)
    masked[dyn_mask] = semantics[dyn_mask]
    return masked


def draw_centered_text(canvas, text, font_scale=1.0, thickness=2):
    (text_w, text_h), _ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX,
                                          font_scale, thickness)
    x = max((canvas.shape[1] - text_w) // 2, 0)
    y = (canvas.shape[0] + text_h) // 2
    cv2.putText(canvas, text, (x, y), cv2.FONT_HERSHEY_SIMPLEX, font_scale,
                (255, 255, 255), thickness, cv2.LINE_AA)


def text_cell(text, width=600, height=86):
    cell = np.full((height, width, 3), (55, 39, 30), dtype=np.uint8)
    draw_centered_text(cell, text, font_scale=1.15, thickness=2)
    cv2.rectangle(cell, (0, 0), (width - 1, height - 1), (205, 210, 218), 2)
    return cell


def framed_cell(image):
    cell = image.copy()
    cv2.rectangle(cell, (0, 0), (cell.shape[1] - 1, cell.shape[0] - 1),
                  (205, 210, 218), 2)
    return cell


def overlay_row_label(image, label):
    image = image.copy()
    overlay = image.copy()
    height = 46
    cv2.rectangle(overlay, (0, 0), (image.shape[1], height), (55, 39, 30), -1)
    cv2.addWeighted(overlay, 0.82, image, 0.18, 0, image)
    cv2.putText(image, label, (12, 31), cv2.FONT_HERSHEY_SIMPLEX, 0.78,
                (255, 255, 255), 2, cv2.LINE_AA)
    return image


def save_png_and_pdf(image, output_dir, stem):
    output_dir.mkdir(parents=True, exist_ok=True)
    png_path = output_dir / f'{stem}.png'
    pdf_path = output_dir / f'{stem}.pdf'
    cv2.imwrite(str(png_path), image)
    Image.fromarray(cv2.cvtColor(image, cv2.COLOR_BGR2RGB)).save(str(pdf_path))
    return png_path, pdf_path


def compose_grid(rows):
    headers = [
        'Plain (C) Pred', 'ProSD-Occ (C) Pred', 'Plain (C) Dynamic',
        'ProSD-Occ (C) Dynamic', 'GT Occ'
    ]
    cells = [text_cell(title) for title in headers]
    for row in rows:
        row_cells = [
            overlay_row_label(row['plain_bev'], row['label']),
            row['prosd_bev'],
            row['plain_dyn_bev'],
            row['prosd_dyn_bev'],
            row['gt_bev'],
        ]
        cells.extend(framed_cell(cell) for cell in row_cells)
    image_rows = []
    column_count = len(headers)
    for start in range(0, len(cells), column_count):
        image_rows.append(cv2.hconcat(cells[start:start + column_count]))
    return cv2.vconcat(image_rows)


def copy_outputs(output_dir, destinations, output_name):
    for destination in destinations:
        destination.mkdir(parents=True, exist_ok=True)
        for suffix in ('.png', '.pdf', '.json'):
            src = output_dir / f'{output_name}{suffix}'
            if src.exists():
                shutil.copy2(src, destination / src.name)


def main():
    args = parse_args()
    config_plain = (ROOT / args.config_plain).resolve()
    config_prosd = (ROOT / args.config_prosd).resolve()
    ckpt_plain = (ROOT / args.ckpt_plain).resolve()
    ckpt_prosd = (ROOT / args.ckpt_prosd).resolve()
    for path in (config_plain, config_prosd, ckpt_plain, ckpt_prosd):
        if not path.exists():
            raise FileNotFoundError(str(path))

    output_dir = args.output_dir.resolve()
    if output_dir.exists() and not args.keep_output_dir:
        shutil.rmtree(output_dir)
    assets_dir = output_dir / 'assets'
    configs_dir = output_dir / 'configs'
    assets_dir.mkdir(parents=True, exist_ok=True)
    configs_dir.mkdir(parents=True, exist_ok=True)

    os.environ.setdefault('PYTHONPATH', str(ROOT))
    _, plain_model = build_model_runner(config_plain, ckpt_plain, args.gpu_id)
    _, prosd_model = build_model_runner(config_prosd, ckpt_prosd, args.gpu_id)

    rows = []
    manifest_rows = []
    for condition_key, label, perturbation in CONDITIONS:
        condition_cfg = configs_dir / f'{condition_key}.py'
        write_reanchor_config(condition_cfg, config_plain, perturbation)
        cfg, dataset, data_loader = build_condition_loader(condition_cfg)
        plain_occ = run_one_prediction(plain_model, data_loader,
                                       args.sample_index)

        # Rebuild the one-sample loader for ProSD so the underlying iterator
        # state and any data containers are fresh.
        _, dataset, data_loader = build_condition_loader(condition_cfg)
        prosd_occ = run_one_prediction(prosd_model, data_loader,
                                       args.sample_index)

        point_cloud_range = (
            dataset._get_eval_point_cloud_range()
            if hasattr(dataset, '_get_eval_point_cloud_range') else None)
        if point_cloud_range is None:
            point_cloud_range = cfg.get('point_cloud_range', None)
        if point_cloud_range is None:
            point_cloud_range = cfg.model.spatials_config.point_cloud_range
        reanchor_mat = build_ego_frame_reanchor_matrix(**perturbation)
        gt = load_occ_gt(dataset, args.sample_index)
        gt = warp_semantics_by_reanchor(
            gt,
            point_cloud_range=point_cloud_range,
            reanchor_mat=reanchor_mat,
            empty_idx=EMPTY_IDX).astype(np.uint8)

        images = {
            'plain_bev': render_occ_bev(plain_occ, EMPTY_IDX, COLOR_MAP),
            'prosd_bev': render_occ_bev(prosd_occ, EMPTY_IDX, COLOR_MAP),
            'plain_dyn_bev': render_occ_bev(dynamic_only(plain_occ),
                                            EMPTY_IDX, COLOR_MAP),
            'prosd_dyn_bev': render_occ_bev(dynamic_only(prosd_occ),
                                            EMPTY_IDX, COLOR_MAP),
            'gt_bev': render_occ_bev(gt, EMPTY_IDX, COLOR_MAP),
        }
        asset_paths = {}
        for name, image in images.items():
            asset_path = assets_dir / f'{condition_key}_{name}.png'
            cv2.imwrite(str(asset_path), image)
            asset_paths[name] = str(asset_path)

        rows.append(dict(label=label, **images))
        manifest_rows.append(
            dict(
                condition=condition_key,
                label=label,
                perturbation=perturbation,
                sample_index=args.sample_index,
                assets=asset_paths))

    figure = compose_grid(rows)
    save_png_and_pdf(figure, output_dir, args.output_name)
    manifest = dict(
        purpose=(
            'Plain(C) and ProSD-Occ(C) qualitative occupancy comparison under '
            'translation and rotation re-anchoring.'),
        sample_index=args.sample_index,
        conditions=manifest_rows,
        columns=[
            'plain_c_pred_all', 'prosd_c_pred_all', 'plain_c_pred_dynamic',
            'prosd_c_pred_dynamic', 'gt_occ'
        ],
        outputs={
            'png': str(output_dir / f'{args.output_name}.png'),
            'pdf': str(output_dir / f'{args.output_name}.pdf'),
        })
    (output_dir / f'{args.output_name}.json').write_text(
        json.dumps(manifest, indent=2), encoding='utf-8')
    copy_outputs(output_dir, [args.project_copy_dir, args.paper_output_dir],
                 args.output_name)
    print(
        json.dumps(
            {
                'output_dir': str(output_dir),
                'paper_png':
                str(args.paper_output_dir / f'{args.output_name}.png'),
                'sample_index': args.sample_index,
            },
            indent=2))


if __name__ == '__main__':
    main()
